[package]
name = "xpallet-gateway-common"
version = "1.0.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"


[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", features = ["derive"], default-features = false }
serde = { version = "1.0", optional = true }

sp-std = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }
# chainx runtime module
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-io = { path = "../../../primitives/io", default-features = false }
xpallet-support = { path = "../../support", default-features = false }
xpallet-assets = { path = "../../assets", default-features = false }

[dev-dependencies]
hex = "0.4"
sp-core = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4" }

[features]
default = ["std"]
std=[
    "codec/std",
    "serde",

    "sp-runtime/std",
    "sp-std/std",

    "frame-support/std",
    "frame-system/std",
    # chainx runtime module
    "chainx-primitives/std",
    "xp-io/std",
    "xpallet-assets/std",
    "xpallet-support/std",
]
